// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"database/sql"
	"github.com/google/wire"
	v1 "github.com/url-shortener/internal/api/v1"
	"github.com/url-shortener/internal/db"
	"github.com/url-shortener/internal/service"
	"github.com/url-shortener/internal/store"
)

// Injectors from wire.go:

func Initialize() (*App, error) {
	router := NewRouter()
	sqlDB, err := db.NewDatabase()
	if err != nil {
		return nil, err
	}
	urlShortenerStore := store.NewStore(sqlDB)
	urlShortenerService := service.NewService(urlShortenerStore)
	urlShortenerAPI := v1.NewAPI(router, urlShortenerService)
	app := NewApp(router, urlShortenerAPI)
	return app, nil
}

func InitializeWithDb(sqlDB *sql.DB) (*App, error) {
	router := NewRouter()
	store := store.NewStore(sqlDB)
	service := service.NewService(store)
	api := v1.NewAPI(router, service)
	app := NewApp(router, api)
	return app, nil
}

// wire.go:

var wireSet = wire.NewSet(
	NewApp,
	NewRouter, store.WireSet,
)

var wireSetWithDb = wire.NewSet(
	wireSet, db.WireSet,
)
